### ISSUE TITLE
ReplayObserverPartition calls Observer.PartitionReplayed which throws exception

### ISSUE THREAD

**Issue by woksin** [Cratis/Chronicle#1543]
`public Task PartitionReplayed(Key partition) => throw new NotImplementedException();`

**Comment by einari** [comment]
The observer should keep track of partitions being replayed. We don't do this today. So methods like `ReplayPartition` and `ReplayPartitionTo` should then add the partition to a collection of replayed partitions. 

The purpose of this is that it should in fact not handle any events coming from the `IAppendedEventsQueue` when replaying. Instead, when the partition replay is done it should then start a catch up job for the partition if the partition is behind. Once the catch up job is done and it doesn't have any more events to work with, it should remove the partition from the state, permitting it to start handling events from the `IAppendedEventsQueue`.

**Comment by woksin** [comment]
But the Observer takes care of all partitions, right? So in the case of observers that handle failing partitions separately it should just not handle events in the partitions that are failing?

**Comment by einari** [comment]
The Observer fans out to the actual subscriber for each partition. If you look at the Handle method on the Observer it creates a key with partition and gets the target grain which is given as a generic argument on the Subscribe() method. The ObserverSubscriber (e.g. Projections, Reducers, Reactors) are then handling per partition.

**Comment by woksin** [comment]
When you mean state here do you talk about tracking replaying partitions in the persisted state or the internal state?
