### ISSUE TITLE
Change API surface for integration to make more sense

### ISSUE THREAD

**Issue by einari** [Cratis/Chronicle#160]
The API is confusing today and hard to reason what does what.
Look at something like below for the methods.

DefineModel => DefineProjection

DefineImport => DefineEventEmitters / DefineEvents

DefineImportMapping =>  DefineInputModelMapping

In addition the builder for `DefineEventEmitters` could be clearer as well:

```csharp
builder.OnPropertyChanged(s => s.Property)....
```

for multiple properties:

```csharp
builder.OnPropertiesChanged(s => s.Property, s => s.OtherProperty)....
```

The `IImportBuilderFor` can also be simplified, not taking more than the target model. We are not interested in the input model at this point. 

The callback for `.AppendEvent()` should have a better context as well. Today it requires navigation through the changeset and incoming, which does not make sense. Instead we could give the dev the incoming instance. 
Multiple overloads could be for this as well, when one need more context. 

Another option is also to provide an overload that gives you a mapper builder that tells how to map from the projected version to an event.

**Comment by Torgeir-Hansen** [comment]
I also think IFromBuilder/ISetBuilder can be merged into a IMapBuilder or something similar, as the current syntax of Set/To is (at least to me) very confusing with regards to how the values flow (is "Set()" defining the target or the source?)
```
    public override void DefineModel(IProjectionBuilderFor<MyProjectionModel> builder)
    {
        builder.From<SomeEvent>(_ => _
                .Set(_ => _.Value1)
                .To(_ => _.Value1)
                .Set(_ => _.Value2)
                .To(_ => _.Value2));
    }
```

I propose a simpler interface, with just a Map() method, with parameters in a flow oriented order (source => target). 
```
    public override void DefineProjection(IProjectionBuilderFor<MyProjectionModel> builder)
    {
        builder.From<SomeEvent>(_ => _
                .Map(_ => _.Value1, _ => _.Value1)
                .Map(_ => _.Value2, _ => _.Value2)
    }
```
(perhaps the overridable method should be called ProjectionBuilder()? 🤔)

**Comment by Torgeir-Hansen** [comment]
As for the method currently known as ```DefineImport()```, where I suggested ```DefineEventEmitters()``` (which at least describes what it performs, although I'm sure an even better name can be found); 
Here I would want an IEventBuilder which defines a .Map() method similar to the proposed IMapBuilder , as the ChangeSet here seems like something I as a developer often will not need to know about when defining the events to be emitted. 
It should also be possible to set hard-coded values here.

So something like this (I've also renamed IImportBuilderFor to IEventBuilderFor):
```
    public override void DefineEventEmitters(IEventBuilderFor<ForsendelsesDetaljer> builder)
    {
        // Trigger on spesific property/propierties change
        builder.OnPropertyChange(s => s.ProjectionValueProperty1)
            .AppendEvent<MyBasicEvent>(_ => _
                    .Map(projection => projection.ProjectionProperty1, @event => @event.ProjectionProperty)
                    .Map(projection => projection.Id, @event => @event.SomeIdentifierProperty)
                    .Map("MyApplication", @event => @event.Origin.Application);

        // Trigger on a changed property in s.ProjectionReferenceProperty, e.g. s.ProjectionReferenceProperty.SomeValue
        builder.OnPropertyChange(s => s.ProjectionReferenceProperty)
            .AppendEvent<MyFancyEvent>(_ => _
                    .Map(projection => projection.ProjectionReferenceProperty.SomeValue, @event => @event.SomeValue)
                    .Map(projection => projection.Id, @event => @event.SomeIdentifierProperty);
                    
        // Do automapping mixed with (followed by) defined mapping
        builder.OnPropertyChange(s => s.ProjectionValueProperty1)
            .AppendEvent<MyBasicEvent>(_ => _
                    // First automatically map properties from the projection to event, where name and type are same.
                    .AutoMap() 
                    // Then automap from Subclass properties directly to event
                    .AutoMap(projection => projection.Subclass, @event => @event) 
                    // Finally, any manually defined mappings
                    .Map(projection => projection.Id, @event => @event.SomeIdentifierProperty)
                   
    }
    ```

**Comment by einari** [comment]
Great input and samples. Love the idea about the `.AutoMap()` for nested objects.

The definition API for the projection is the same API used for regular projections.

The reason for the division of operations today (`.Set().To()`) is for readability and flexibility. There are today methods for doing more than just setting it to a value from the event. There are things like `.ToEventSourceId()` and we could have things like `.ToCurrentDate()` or other operations. With a single `.Map()` method it becomes rigid and less readable as you can only work on overloads. 

It could be a rename of `.Set()` to `.Map()` but I’m unsure if that reflects accurately on what we’re trying to do. 

The projections API in particular has been an attempt at mimicking a query language in a way, a cross between SQL and LINQ in mindset. **from EventA, EventB, EventC select { PropA = EventA.Prop, PropB = EventB.Prop, PropC = EventC.Prop }**.

**Comment by einari** [comment]
Notes from a Slack discussion.
A possibility would be to have `.Set()` take an expression that gets parsed rather than splitting it into a fluent interface, making it more intuitive to work with:

```csharp
        builder.From<SomeEvent>(_ => _
                .Set((m,e) => m.Value1 = e.Value1)
                .Set((m,e) => m.Value2 = e.Value2)
```

This would allow for literals in the same way:

```csharp
        builder.From<SomeEvent>(_ => _
                .Set((m) => m.Value1 = 42)
                .Set((m) => m.Value2 = "Magic String")
```

For things in the EventContext or other formalized values these could be given as part of the expression:

```csharp
        builder.From<SomeEvent>(_ => _
                .Set((m) => m.Value1 = EventContext.Occurred)
                .Set((m) => m.Value2 = DateTimeExpressions.UtcNow)
```

The expressions would be C# `Expression<>` and we would need to validate them with the operations we support. They are not to be mistaken as callbacks. Clear error messages to the developer would be necessary.

**Comment by einari** [comment]
Closing this, as we will circle back to integration at a later stage. 
The goal is to let this be a Kernel service, and the clients just specifying how it should do it in a declarative manner, similar to what we have, but not calling the client. This would enable the server to have these as jobs.
